// <auto-generated />
namespace Document_Approval_Project_BE.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
<<<<<<<< Updated upstream:Document-Approval-Project-BE/Migrations/202403250722062_UPDATE-DB.Designer.cs
    public sealed partial class UPDATEDB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UPDATEDB));
        
        string IMigrationMetadata.Id
        {
            get { return "202403250722062_UPDATE-DB"; }
========
    public sealed partial class dbv1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dbv1));
        
        string IMigrationMetadata.Id
        {
            get { return "202404010514188_db-v1"; }
>>>>>>>> Stashed changes:Document-Approval-Project-BE/Migrations/202404010514188_db-v1.Designer.cs
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
